### ISSUE TITLE
XCode 16 & Nodle iOS SDK build issues - dyld: Symbol not found

### ISSUE THREAD

**Issue by Dardev12** [NodleCode/NodleSDK-Release#5]
# Symbol Not Found Error with NodleSDK and SQLite.swift

## Description

When building and running the iOS app, I encounter a `dyld` error related to a missing symbol. This error occurs despite following the setup instructions for the Podfile.

Nodle Doc -> [link](https://docs.nodle.com/nodle-ios-sdk#block-e443574ff4aa475295f96e1dd6fed74c)

## Error Message

```
dyld[8149]: Symbol not found: __ZN5swift39swift51override_conformsToSwiftProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEN7__swift9__runtime4llvm9StringRefEPFPKNS_35TargetProtocolConformanceDescriptorIS1_EES4_S8_SC_E
  Referenced from: <26DAD288-6F4C-3FB6-A088-73E5D7128A40> /private/var/containers/Bundle/Application/AF109122-2129-4AFD-A304-BE8062B871F4/iosLandApp.app/Frameworks/NodleSDK.framework/NodleSDK
  Expected in:     <B7849A53-EE95-3CE8-A141-6F8679DB098D> /private/var/containers/Bundle/Application/AF109122-2129-4AFD-A304-BE8062B871F4/iosLandApp.app/Frameworks/SQLite.framework/SQLite
```

## Environment

- iOS Target Version: 14.1
- NodleSDK Version: 0.0.23-night
- SQLite.swift Version: 0.15.3
- Xcode Version: 16.0

## Podfile

```ruby
platform :ios, '14.1'

target 'iosLandApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'GoogleMaps', '8.4.0'
  pod 'GooglePlaces', '7.1.0'
  pod 'GoogleUserMessagingPlatform'
  pod 'ToastSwiftUI'
  pod 'NodleSDK', :git => 'https://github.com/NodleCode/NodleSDK-Release', :branch => 'night', :tag => '0.0.23-night'
  pod 'SQLite.swift', '~> 0.15.3'
  pod 'SwiftCBOR', '~> 0.4.5'
  pod 'SwiftProtobuf', '~> 1.26.0'
  pod 'Google-Mobile-Ads-SDK'
  pod 'SwiftLint'
  pod 'Shuffle-iOS'
  pod 'PopBounceButton'
  pod 'pop', '~> 1.0'
  
  # Test targets...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
```

## Additional Information

- I have tried running `pod deintegrate` and `pod install` again.
- I have deleted the Podfile.lock and workspace and let CocoaPods regenerate them.
- I have closed and reopened the workspace after these actions.

## Questions

1. Is there a known compatibility issue between NodleSDK 0.0.23-night and SQLite.swift 0.15.3?
2. Are there any specific build settings or configurations required for NodleSDK that I might be missing?
3. Could this be related to the Xcode version ?

**Comment by nikiizvorski** [comment]
There is no public version of the SDK on XCode 16 just yet. It will be in near future. Please use XCode 15 and that would work fine. There is a linker issue in the XCode 16 versions.
